### PR TITLE
Early returns, closing handlers only

### PR DESCRIPTION
**Pull request by rredpoppy**
Not tested, please verify.

### CODE REVIEW

**Comment by rredpoppy** [comment]
You are correct, sorry for missing that

**Comment by mihaioltean** [comment]
In which case do you return E_NO_SIZE ? There is no such return in get_file_size function ...

**Comment by rredpoppy** [comment]
`ftell` [returns -1 if unsuccessful](http://www.cplusplus.com/reference/cstdio/ftell/). `strerror(errno)` can be used to retrieve error message in that case

**Comment by mihaioltean** [comment]
Ok. 
Just 2 fixes are needed:
#define E_NO_SIZE = -1 -> remove =
and add a ; after return E_CANNOT_OPEN_FILE 

waiting

**Comment by mihaioltean** [comment]
#define E_NO_SIZE = -1 ; please remove =

**Comment by rredpoppy** [comment]
I would leave the E_NO_SIZE, at least it gives an indication of the failure. Also, please be aware that the method [is not compliant to get the file size](https://wiki.sei.cmu.edu/confluence/display/c/FIO19-C.+Do+not+use+fseek%28%29+and+ftell%28%29+to+compute+the+size+of+a+regular+file), either on [POSIX](https://stackoverflow.com/questions/9135256/are-there-cases-where-fseek-ftell-can-give-the-wrong-file-size) nor on Windows. In general, assuming there is a platform independent way of getting system info is to be treated with caution

**Comment by mihaioltean** [comment]
just remove the = operator ... that is all

**Pull request merged**
